version: '3'


services:
    mariadb:
        container_name: mariadb
        env_file: .env
        build: ./requirements/mariadb
        restart: always
        networks:
            - intra
        volumes:
            - db-v:/var/lib/mysql

    wordpress:
        container_name: wordpress
        env_file: .env
        build: ./requirements/wordpress
        restart: always
        volumes:
            - www-v:/var/www
        networks:
            - intra
        depends_on:
           - mariadb

    nginx:
        container_name: nginx
        env_file: .env
        build: ./requirements/nginx
        restart: always
        ports:
            - "443:443"
        volumes:
            - www-v:/var/www
        networks:
            - intra
        depends_on:
            - wordpress
networks:
    intra:
        driver: bridge

volumes:
  db-v:
    name: db-v
    driver: local
    driver_opts:
      device: '/home/sanghyol/data/db'
      type: 'none'
      o: 'bind'

  www-v:
    name: www-v
    driver: local
    driver_opts:
      device: '/home/sanghyol/data/wordpress'
      type: 'none'
      o: 'bind'